// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj4rHLsjSYxJpQ9xdo-6PTNXm0YqK2Bek',
    appId: '1:695103503048:ios:647bf8cb12f62e6c1683fd',
    messagingSenderId: '695103503048',
    projectId: 'flutter-project-61491',
    storageBucket: 'flutter-project-61491.firebasestorage.app',
    iosBundleId: 'com.example.petCare1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTrk-MzAft4WrkoT26-fyWYvilsIjc0rE',
    appId: '1:695103503048:web:d2c150a90520f7fd1683fd',
    messagingSenderId: '695103503048',
    projectId: 'flutter-project-61491',
    authDomain: 'flutter-project-61491.firebaseapp.com',
    storageBucket: 'flutter-project-61491.firebasestorage.app',
    measurementId: 'G-6V8KVMRRXZ',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTrk-MzAft4WrkoT26-fyWYvilsIjc0rE',
    appId: '1:695103503048:web:d2c150a90520f7fd1683fd',
    messagingSenderId: '695103503048',
    projectId: 'flutter-project-61491',
    authDomain: 'flutter-project-61491.firebaseapp.com',
    storageBucket: 'flutter-project-61491.firebasestorage.app',
    measurementId: 'G-6V8KVMRRXZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj4rHLsjSYxJpQ9xdo-6PTNXm0YqK2Bek',
    appId: '1:695103503048:ios:647bf8cb12f62e6c1683fd',
    messagingSenderId: '695103503048',
    projectId: 'flutter-project-61491',
    storageBucket: 'flutter-project-61491.firebasestorage.app',
    iosBundleId: 'com.example.petCare1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0-fbH4N5pT-e-nmahlV3pmdG3F74mM1s',
    appId: '1:695103503048:android:f3450fc6bad269431683fd',
    messagingSenderId: '695103503048',
    projectId: 'flutter-project-61491',
    storageBucket: 'flutter-project-61491.firebasestorage.app',
  );

}